# Generated by Django 5.1.4 on 2024-12-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state_name', models.CharField(max_length=32)),
                ('pincode', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
