# Generated by Django 5.1.4 on 2024-12-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_accident_latitude_alter_accident_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=64),
        ),
    ]
