# Generated by Django 5.1.4 on 2025-01-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistsOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_available_quantity', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
            options={
                'unique_together': {('hospital', 'resource')},
            },
        ),
    ]
