# Generated by Django 5.1.4 on 2025-01-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accident_patient_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=64),
        ),
    ]
