# Generated by Django 5.1.4 on 2025-01-14 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hospital_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
