# Generated by Django 5.1.4 on 2025-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_patient_blood_group_alter_patient_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistsof',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
